version: '2'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.1
    command:
      - redpanda
      - start
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,external://localhost:19092
      - --smp 1
      - --memory 1G
      - --default-log-level=info
    ports:
      - "9092:9092"
      - "19092:19092"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          clientId: console
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: kafka-connect
              url: http://connect:8083
    ports:
      - "8080:8080"
    links:
      - redpanda
      - connect
    depends_on:
      - redpanda
      - connect

  connect:
    image: docker.redpanda.com/redpandadata/connectors:v1.0.13
    environment:
      CONNECT_HEAP_OPTS: -Xms1G -Xmx1G
      CONNECT_BOOTSTRAP_SERVERS: redpanda:9092
      CONNECT_PLUGIN_PATH: /opt/kafka/connect-plugins
      CONNECT_ADDITIONAL_CONFIGURATION: |
        key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
        value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
        group.id=connectors-group
        offset.storage.topic=_connectors_offsets
        config.storage.topic=_connectors_configs
        status.storage.topic=_connectors_status
        config.storage.replication.factor=-1
        offset.storage.replication.factor=-1
        status.storage.replication.factor=-1
    volumes:
      - $PWD/lib/build/libs:/opt/kafka/connect-plugins
    ports:
      - "8083:8083"
    links:
      - redpanda
    depends_on:
      - redpanda